environment:
  SECUREPSD:
    secure: 6sB3RRUjx/vTjKDEdZP5KA==
    
  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
    
install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project.
  - "pip install -r requirements-full.txt"
  - "pip install wheel"
  - "pip install cython"
  - "pip install twine"


build_script:
  # Build the compiled extension
  - "python setup.py build"

after_test:

  - "python setup.py bdist_wheel"
  
  # Specify account details for testPyPI
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     testpypi                                >> %USERPROFILE%\\.pypirc
  - echo [testpypi]                                  >> %USERPROFILE%\\.pypirc
  - echo repository=https://testpypi.python.org/pypi >> %USERPROFILE%\\.pypirc
  - echo username=pyodps                             >> %USERPROFILE%\\.pypirc
  - echo password=%SECUREPSD%                        >> %USERPROFILE%\\.pypirc
  
  # Workaround required to ensure setup.py finds the .pypirc under Windows
  #- set HOME=%USERPROFILE%

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
    
on_success:  
  #- "twine upload -u pyodps -p %SECUREPSD dist\*"
  - "python setup.py register -r https://testpypi.python.org/pypi"
  - "twine upload -r testpypi dist/*"
 

