[build-system]
requires = [
    "setuptools<64",
    "wheel",
    "numpy==1.14.5; python_version<='3.7' and platform_machine!='aarch64'",
    "oldest-supported-numpy; python_version>'3.7'",
    "cython>=3.0; platform_system!='Windows'",
]
