# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/xstreampack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/xstreampack.proto',
  package='',
  serialized_pb='\n\x17proto/xstreampack.proto\"3\n\x0bXStreamPack\x12\x11\n\tpack_data\x18\x01 \x02(\x0c\x12\x11\n\tpack_meta\x18\x02 \x01(\x0c')




_XSTREAMPACK = _descriptor.Descriptor(
  name='XStreamPack',
  full_name='XStreamPack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pack_data', full_name='XStreamPack.pack_data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pack_meta', full_name='XStreamPack.pack_meta', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['XStreamPack'] = _XSTREAMPACK

class XStreamPack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _XSTREAMPACK

  # @@protoc_insertion_point(class_scope:XStreamPack)


# @@protoc_insertion_point(module_scope)
